branches:
  only:
    - source
cache:
  apt: true
env: 
  - "HUGO_VERSION=0.10"

before_install:
  - mkdir -p ${HOME}/temp
  - cd ${HOME}/temp
  - curl --compressed --create-dirs --location --remote-name --remote-time --retry 3 --show-error --url https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux_amd64.tar.gz
  - tar -xzf hugo_${HUGO_VERSION}_linux_amd64.tar.gz

install:
  - sudo mv hugo_${HUGO_VERSION}_linux_amd64/hugo_${HUGO_VERSION}_linux_amd64 /usr/local/bin/hugo
  - sudo apt-get install python-pygments
  - cd ${TRAVIS_BUILD_DIR}
  - rm -Rf ${HOME}/temp 

script:
  - hugo -s .

after_success:
  - git config --global user.email "arenard@travis-ci.org"
  - git config --global user.name "Travis-CI"
  - git config --global push.default simple
  - mkdir -p ${HOME}/temp
  - git clone --branch=master git://github.com/arenard/arenard.github.io.git arenard/arenard.github.io
  - mv ${TRAVIS_BUILD_DIR}/public $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git add -A .
  - git commit -m "test"
  - ls -la
  - git push
