branches:
  only:
    - source
cache:
  apt: true

before_install:
  - curl --compressed --create-dirs --location --remote-name --remote-time --retry 3 --show-error --url https://github.com/spf13/hugo/releases/download/v0.10/hugo_0.10_linux_amd64.tar.gz
install:
  - tar -xzf hugo_0.10_linux_amd64.tar.gz
  - sudo mv hugo_0.10_linux_amd64/hugo_0.10_linux_amd64 /usr/local/bin/
  - sudo apt-get install python-pygments

script:
  - hugo_0.10_linux_amd64 -s .

after_success:
  - git config --global user.email "arenard@travis-ci.org"
  - git config --global user.name "Travis-CI"
  - git branch
  - git checkout master
  - git checkout source public
  - git mv public .
  - git add -A .
  - git commit -m "test"
