branches:
  only:
    - source
cache:
  apt: true
env: 
  - HUGO_VERSION="0.10" secure: "dgRBYKR0A5HEtll5OlR+c5HMkAziELKuCxF7Pm6lubZJBR8NN5hWghlb6yQNjEQRYMPuYMprbs931sHjEsF7nvWCn+Chq1ixSG4HJGSWo/4dh6lZ1AgwpuQk0kcDQs28ut8+A3q7xA9VJmv/NamSXzZccBSiCjbFLslWqfReVFc=" 

before_install:
  - mkdir -p ${HOME}/temp
  - cd ${HOME}/temp
  - curl --compressed --create-dirs --location --remote-name --remote-time --retry 3 --show-error --url https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux_amd64.tar.gz
  - tar -xzf hugo_${HUGO_VERSION}_linux_amd64.tar.gz

install:
  - sudo mv hugo_${HUGO_VERSION}_linux_amd64/hugo_${HUGO_VERSION}_linux_amd64 /usr/local/bin/hugo
  - sudo apt-get install python-pygments
  - cd ${TRAVIS_BUILD_DIR}
  - rm -Rf ${HOME}/temp 

script:
  - hugo -s .

after_success:
  - git config --global user.email "arenard@travis-ci.org"
  - git config --global user.name "Travis-CI"
  - git config --global push.default simple
  - mkdir -p ${HOME}/temp
  - cd ${HOME}/temp
  - git clone --branch=master https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git ${TRAVIS_REPO_SLUG}
  - cd ${TRAVIS_REPO_SLUG}
  - mv ${TRAVIS_BUILD_DIR}/public/* .
  - git add -A .
  - git commit -m "Travis build ${TRAVIS_BUILD_NUMBER}"
  - git push  
